name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    steps:
      - name: Print Environment Variables
        run: |
          echo "DATABASE_URL: $DATABASE_URL"
          echo "TEST_USERNAME: $TEST_USERNAME"
          echo "TEST_PASSWORD: $TEST_PASSWORD"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libpq-dev 
          cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
