name: Rust CI/CD  

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}  
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Postgres  
      run: |  
        sudo apt update
        sudo apt install -y libpq-dev

    - name: Build  
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Deploy to Render
      uses: render-examples/render-deploy@main
      env:  
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
      with:
        service-name: rishabh-login
        render-token: ${{ secrets.RENDER_TOKEN }}
        branch: master
