name: Rust CI/CD  

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}  
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo 
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Postgres
        run: |
          sudo apt update
          sudo apt install -y libpq-dev

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
