name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ env.DATABASE_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libpq-dev 
        cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
